const mongoose = require("mongoose");

//define a comment schema for the database
const PointSchema = new mongoose.Schema({
  name: String, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
  index: Number,  
});

PointSchema.statics.findAndModify = function (query, sort, doc, options, callback) {
    return this.collection.findAndModify(query, sort, doc, options, callback);
  };
// compile model from schema
module.exports = mongoose.model("point", PointSchema);
