const mongoose = require("mongoose");

//define a comment schema for the database
const StarSchema = new mongoose.Schema({
  name: String, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
  content: String,
  index: Number,  
  myth_img: String,
  const_img: String,
});

// compile model from schema
module.exports = mongoose.model("star", StarSchema);
